---
version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-79
  brakeman:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  bundler-audit:
    enabled: true
  reek:
    enabled: true
exclude_patterns:
- config/
- db/
- spec/
