before_script:
  - apt-get update -qq && apt-get install -y -qq postresql nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rubocop:
  script:
    - bundle exec rubocop

rspec:
  script:
    - bundle exec rspec
