AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'features/**/*'
Rails:
  Enabled: true

Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 132
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'app/models/*'

Rails/HttpPositionalArguments: # удалить этот запрет для Rails 5
  Exclude:
    - 'spec/controllers/*'
