AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.1
  Exclude:
    - 'bin/*'
    - 'tmp/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'features/**/*'
    - 'coverage/*'
    - 'Guardfile'
    - 'vendor/*'
Rails:
  Enabled: true

Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 132
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'app/models/*'

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb

# TODO:
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
