AllCops:
  require: rubocop-rspec
  TargetRubyVersion: 2.5.1
  TargetRailsVersion: 5.2
  Exclude:
    - 'lib/**/*'
    - 'bin/*'
    - 'tmp/*'
    - 'db/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'features/**/*'
    - 'coverage/*'
    - 'Guardfile'
    - 'node_modules/**/*'
    - 'vendor/**/*'
Rails:
  Enabled: true

Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 132
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Exclude:
    - app/models/*
Metrics/ClassLength:
  Exclude:
    - app/controllers/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb

# TODO:
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
