require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-faker
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - 'lib/tasks/*'
    - 'lib/paperclip_processors/*'
    - 'bin/*'
    - 'tmp/*'
    - 'db/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'coverage/*'
    - 'Guardfile'
    - 'node_modules/**/*'
    - 'vendor/**/*'
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Exclude:
    - app/models/*
    - spec/**/*
Metrics/ClassLength:
  Exclude:
    - app/controllers/*
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*_spec.rb
Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb
Layout/LineLength:
  Max: 132
Lint/RaiseException:
  Enabled: true
Layout/SpaceAroundMethodCallOperator: 
  Enabled: true
Style/ExponentialNotation:
  Enabled: true

# TODO:
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec:
  Enabled: false
Lint/UselessAssignment:
  Exclude:
    - spec/**/*_spec.rb
    - spec/features/*.rb
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
Lint/LiteralAsCondition:
  Enabled: false
