# inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'features/**/*'
Rails:
  Enabled: true

Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 132
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
