language: ruby
rvm:
  - 2.3.1
cache: bundler
before_script:
  - cp config/database.yml{.example,}
  - cp config/ldap.yml{.example,}
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rspec spec/
  - bundle exec rubocop
