language: ruby
rvm:
  - 2.4.2
cache: bundler
bundler_args: --without production
before_script:
  - cp config/database.yml{.example,}
  - cp config/ldap.yml{.example,}
  - bundle exec rake db:create db:migrate db:seed --trace
script:
  # change ldap-auth to database-auth 
  - sed -i 's/config.authentication_keys = \[ :username \]/config.authentication_keys = \[ :email \]/' config/initializers/devise.rb
  - sed -i 's/devise :ldap_authenticatable/devise :database_authenticatable/g' app/models/user.rb
  - sed -i 's/before_save :ldap_email/# before_save :ldap_email/g' app/models/user.rb

  - bundle exec rspec --exclude-pattern "spec/features/*_spec.rb"

  # - bundle exec rake db:seed
  - gem install rubocop

branches:
 only:
  - master

