language: ruby
rvm:
  - 2.2.2
cache: bundler
before_script:
  - cp config/database.yml{.example,}
  - bundle exec rake db:setup
  - npm install bower
  - bundle exec rake bower:install
script:
  - bundle exec rspec spec/
