language: ruby
rvm:
  - 2.3.1
cache: bundler
before_script:
  - cp config/database.yml{.example,}
  - cp config/ldap.yml{.example,}
  - bundle exec rake db:create db:migrate
script:
  # change ldap-auth to database-auth 
  - sed -i 's/config.authentication_keys = \[ :username \]/config.authentication_keys = \[ :email \]/' config/initializers/devise.rb
  - sed -i 's/devise :ldap_authenticatable/devise :database_authenticatable/g' app/models/user.rb
  - sed -i 's/before_save :get_ldap_lastname/# before_save :get_ldap_lastname/g' app/models/user.rb

  - bundle exec rspec spec/r*
  - bundle exec rspec spec/models/
  - bundle exec rake db:seed
