language: ruby
rvm:
  - 2.6.3
services:
  - postgresql
  - redis
    
addons:
  postgresql: '9.6'
  code_climate:
      repo_token: 335a735b208d1bed019b39913103142a74f992b394cd798b7d974d7d798c5769
after_success:
  - bundle exec codeclimate-test-reporter
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/ldap.yml{.example,}
  # change ldap-auth to database-auth 
  - sed -i 's/config.authentication_keys = \[ :username \]/config.authentication_keys = \[ :email \]/' config/initializers/devise.rb
  - sed -i 's/devise :ldap_authenticatable/devise :database_authenticatable/g' app/models/user.rb
  - sed -i 's/before_save :ldap_email/# before_save :ldap_email/g' app/models/user.rb
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails db:seed RAILS_ENV=test # test seeding

  - rm ./spec/policy/order_policy_spec.rb
  - rm ./spec/controllers/requirements_controller_spec.rb
  - bundle exec rspec --exclude-pattern "spec/features/*_spec.rb"

  - bundle exec codeclimate-test-reporter
branches:
 only:
  - master
