# docker-compose.yml
version: '3.2'

services:
  db:
    image: postgres
  web:
    build: .
    ports: 
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
    # ...
