# docker-compose.yml
# docker-compose up -d
version: '3'

services:
  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data:cached
volumes:
  db-data: