# docker-compose.yml
# docker-compose build
# docker-compose run web bundle install
# docker-compose run web rake db:create
# docker-compose run web rake db:setup
# docker-compose up
# docker-compose down
# docker-compose run web rake -T bp1step:
version: '3'

services:
  db:
    image: postgres:11-alpine
    container_name: bp1step_pg
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:cached
  redis:
    image: redis:5-alpine
    container_name: bp1step_redis
    ports:
    - "6379"

  web:
    build:
      context: .
    container_name: bp1step
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid"
    # command: bash -c "foreman start -f Procfile.dev-server"
    environment:
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
volumes:
  db-data:
